export const tabSize = 32;

export const headerFooterTabStyle: React.CSSProperties = {
  position: 'absolute',
  left: '55%',
  transform: 'translateX(-50%)',
  width: tabSize,
  height: tabSize,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  background: '#f8f9fa',
  border: '1.5px solid #dee2e6',
  borderRadius: '0 0 16px 16px',
  boxShadow: '0 2px 8px rgba(0,0,0,0.07)',
  cursor: 'pointer',
  zIndex: 50,
  color: '#495057',
  fontSize: 18,
  opacity: 0.7,
  transition: 'background 0.2s, opacity 0.2s',
  userSelect: 'none',
};

export const leftPanelTabStyle: React.CSSProperties = {
  position: 'fixed',
  top: '20%',
  // right: -tabSize / 2,
  transform: 'translateY(-50%)',
  width: tabSize,
  height: tabSize,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  background: '#f8f9fa',
  border: '1.5px solid #dee2e6',
  borderRadius: '0 16px 16px 0',
  boxShadow: '0 2px 8px rgba(0,0,0,0.07)',
  cursor: 'pointer',
  zIndex: 50,
  color: '#495057',
  fontSize: 18,
  opacity: 0.7,
  transition: 'background 0.2s, opacity 0.2s',
  userSelect: 'none',
};

export const leftPanelTabHiddenStyle: React.CSSProperties = {
  position: 'fixed',
  top: '20%',
  left: 0,
  transform: 'translateY(-50%)',
  width: tabSize,
  height: tabSize,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  background: '#f8f9fa',
  border: '1.5px solid #dee2e6',
  borderRadius: '0 16px 16px 0',
  boxShadow: '0 2px 8px rgba(0,0,0,0.07)',
  cursor: 'pointer',
  zIndex: 50,
  color: '#495057',
  fontSize: 18,
  opacity: 0.7,
  transition: 'background 0.2s, opacity 0.2s',
  userSelect: 'none',
};
